name: Build images and push to Docker Hub

on: 
  push:
      branches: 
        - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the tagged Docker image dev for client
        run: docker build ./client --file ./client/Dockerfile.dev --tag hagli8/react-test
      
      - name: Run tests
        run: docker run -e CI=true hagli8/react-test npm test
  cd:
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get short SHA
        id: githash
        run: echo "::set-output name=shortsha::$(echo ${GITHUB_SHA::7})"

      - name: Create deployment
        run: bash ./scripts/deploy.sh
        env:
          SHA: ${{ steps.githash.outputs.shortsha }}